# Generated by Django 3.1.2 on 2020-10-19 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer_details',
            fields=[
                ('username', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=45, primary_key=True, serialize=False)),
                ('Current_balance', models.IntegerField()),
            ],
        ),
    ]
