# Generated by Django 3.1.2 on 2020-10-20 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bankingapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='customer_details',
            new_name='User',
        ),
    ]
